//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Songkick.Phone.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Songkick.Phone.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string AccountAction {
            get {
                return ResourceManager.GetString("AccountAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my artists.
        /// </summary>
        public static string ArtistsAction {
            get {
                return ResourceManager.GetString("ArtistsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        public static string ArtistsPivotItem {
            get {
                return ResourceManager.GetString("ArtistsPivotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar.
        /// </summary>
        public static string CalendarAction {
            get {
                return ResourceManager.GetString("CalendarAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALENDAR.
        /// </summary>
        public static string CalendarTitle {
            get {
                return ResourceManager.GetString("CalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENT DETAILS.
        /// </summary>
        public static string EventDetailsTitle {
            get {
                return ResourceManager.GetString("EventDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locations.
        /// </summary>
        public static string LocationsAction {
            get {
                return ResourceManager.GetString("LocationsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY ARTISTS.
        /// </summary>
        public static string MyArtistsTitle {
            get {
                return ResourceManager.GetString("MyArtistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to near you.
        /// </summary>
        public static string NearYouPanoramaItem {
            get {
                return ResourceManager.GetString("NearYouPanoramaItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans.
        /// </summary>
        public static string PlansPivotItem {
            get {
                return ResourceManager.GetString("PlansPivotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchAction {
            get {
                return ResourceManager.GetString("SearchAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trackings.
        /// </summary>
        public static string TrackingPanoramaItem {
            get {
                return ResourceManager.GetString("TrackingPanoramaItem", resourceCulture);
            }
        }
    }
}
